version: "3"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - shared

networks:
  shared:
    external:
      name: shared

volumes:
  redisdata:
  